<?php

namespace BeeCMS\SearchBundle\Entity;

/**
 * SearchIndexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchIndexRepository extends \Doctrine\ORM\EntityRepository
{
}
